#! /bin/sh
# /etc/init.d/sendIP

case "$1" in
  start)
    echo "Starting sendIP"
    # run application you want to start
    python /home/pi/sendIP.py &
    ;;
  stop)
    echo "Stopping sendIP"
    # kill application you want to stop
    kill -15 $(ps -ef | grep "python /home/pi/sendIP.py" | awk '{print $2}' | sed -n 1p)
    ;;
  *)
    echo "Usage: /etc/init.d/sendIP {start|stop}"
    exit 1
    ;;
esac

exit 0
